language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "8"

script:
  - yarn install
  - yarn run lint
  - yarn run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
