language: node_js

os:
  - linux
  - osx

node_js:
  - "node"

script:
  - yarn install
  - yarn run lint
  - gatsby build --prefix-paths

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
